apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-bind 
subjects:
  - kind: User 
    name: admin-bind-user 
    apiGroup: rbac.authorization.k8s.io
roleRef:
  - kind: ClusterRole 
    name: admin 
    apiGroup: rbac.authorization.k8s.io