apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: akshay
spec:
  groups:
  - system:authenticated
  request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlJQ1ZqQ0NBVDRDQVFBd0VURVBNQTBHQTFVRUF3d0dZV3R6YUdGNU1JSUJJakFOQmdrcWhraUc5dzBCQVFFRgpBQU9DQVE4QU1JSUJDZ0tDQVFFQXVqdFJsTi9iZHpSTGhBV0RJU1E4SEJoNzBFZndtaGlqa1RPVXJ2Q3lubXpOCjB0UkRxMmZ6VDdCU0lxdDF0eUQ0VG96eXQrYllNZFIzT1EranVXUlU4TWZtSXdxWGUrYThXSVBrVWVENGhtL2wKWUo4VWtKbUZUaTZ6TFc3bTBqQTJubTJqMGUweURtb1gyeGZZUEV2blc1Vks1OFBFYmxjdm51SWdPTExuNG90SQpzeGEzaDdhU29PUG9UMHJqaTRPWXNmMjRPam8xSzRJMW9jRmZ0M2kzM2NHOFdkQy9JYWZ5SGpnbHFnNStXd21zClJaUlFOOC9YMEQ1Z0E0ellMVk5xWFkzWE15aDJXdkFZdEV1K0hnRnVrNm1ZYzlrRlY2bWk5MldHWUFrekt3a0IKa09xenZYR3FrRldQdG1EM0dUTXRVbkZGalB2Rk9aeENGSFdFOUlWbFN3SURBUUFCb0FBd0RRWUpLb1pJaHZjTgpBUUVMQlFBRGdnRUJBSEJOSHYyTUZzQ0cwaVF4WUIyU2N0blB2d2hNWkRHMDNSUkpseFRlaWdUcFVSV3VpdVdECm1SMVpvY3NWRlB3NXN0eFY5UHphZDVRTTFBbS9pelA2VXdNUGpWcmZNZzByWmoxcFZwc0xEeVBsN3orV1hTeEcKemVpLzdzd1VQWXVIVFdDYlp4eUVIdUEwb1dZR0ZzUVVydmhOSStnZXdjTjN1UTBuM2lNdFRVRWdXcGQwQTQ5OAp4U2ZYcVAxRWVYVmhqY1ViZDZ4REI3Yk51MEVhU1Fab3A0cU83cmpydUtYT0JDUG9teU00OXNSdEZia2dnVmlJClYrbVJoQkU0VVpmRDVVRVhWdzhyWkU5UWs1QU9rQ1VvWTlBNjhFYU0xUjVkblN0d1BSWXZ3UjB0aFVqZXJTRWwKbkUwOURMZGRLNFhtSGlnZmhxTjhOL2p3M2s4eGpmV1I0dlk9Ci0tLS0tRU5EIENFUlRJRklDQVRFIFJFUVVFU1QtLS0tLQo=
  usages:
  - digital signature
  - key encipherment
  - server auth
